### ISSUE TITLE
About update

### ISSUE THREAD

**Issue by rafaelsabino** [mahabub81/covid-19-api#1]
Good afternoon. I would like to use this dump in my project, but I would like to know how the update is done. Is it manual? I needed an automatic update to generate my bank that feeds my graphs, can I count on yours or is it done manually?

**Comment by mahabub81** [comment]
Currently, it is manual. I am working on V2 API and automatic update. it might need next 3/4 days.

**Comment by mahabub81** [comment]
**I will close the issue, when the Automatic update is done.**

**Comment by rafaelsabino** [comment]
all right, thank you very much for the answers. I hope you can, I'll wait.

**Comment by mahabub81** [comment]
@rafaelsabino  I did setup the automatic update process and still checking.

**Comment by rafaelsabino** [comment]
Great. I am very grateful @mahabub81 👍
